server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://ec2-44-206-214-233.compute-1.amazonaws.com:5432/d8gsebqpodtflc
    username: soyyhudsrejqta
    password: daf0f0973bd5e30e01627f7413958ed6a06c3571ef48a47be6a16f4bc545a039
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 20000
      driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      import-check:
        enabled: false
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    enabled: false
    
        
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

api-base-path: /api/v1
front-end-url: *